name = "MultiBeamCalculator"
uuid = "a8b5cac8-97a3-4729-89b4-5e5d4f751bee"
authors = ["Angel Rodriguez-Fernandez <rodrigfa@xfel.eu>", "James Wrigley <james.wrigley@xfel.eu>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CUDA = "5"
DelimitedFiles = "1"
FFTW = "1"
KernelAbstractions = "0.9"
ProgressMeter = "1"
Statistics = "1"
